### ISSUE TITLE
Related to the stutter issue

### ISSUE THREAD

**Issue by NNinja1255** [Def-Try/FancyErrors#1]
Here is results I got using "Find Laggy Hooks":

`Here are the 16 laggiest hooks found during the last 510 frames:`
` Identifier ------------------------------------------------------------ Impact  Executions  Mean t /f  Max time `
` Timer "fancyerrors_checker"                                             1984%   12          11937.76us 529341us `
`  in "lua/autorun/client/cl_fancyerrors.lua" (lines 126 to 153),`
`  found in Workshop addon « FancyErrors »`

It seems to be coming from the "fancyerrors_checker" timer inside of cl_fancyerrors.lua.

**Comment by Def-Try** [comment]
does that happen now? what profiler did you use?

**Comment by NNinja1255** [comment]
> does that happen now? what profiler did you use?

This issue was reported before you committed your stutter fixes. I'm not sure if it happens now yet, I have to test it again.
